### FOLDERS ###

VIDEOS_FOLDER = "./Videos/"
IMAGES_FOLDER = "./Images/"
SOUNDS_FOLDER = "./Sounds/"


### Images ###

IMAGES_CODEC = '.png'

### TTS ###
TTS_API_URL = "https://api.voicerss.org"
TTS_API_KEY = "d1ed7ae9941143b29f21fcbfb0f72afe"
TTS_API_LANGUAGE = "en-us"
TTS_API_VOICE = "Mike"
TTS_API_RATE = 1
TTS_API_CODEC = ".mp3"
TTS_API_FORMAT = "ulaw_44khz_stereo"

### REDDIT ####

REDDIT_API_KEY = "jEszfi31LAMwuQAFIjD_nw"
REDDIT_API_SECRET = "Z7TgJRGwFqz_Ss99qGX0GFKvPmV_9Q"
REDDIT_NUM_PARTS = 15
REDDIT_SUBREDDIT = 'trueoffmychest'
REDDIT_URL = "https://www.reddit.com/r/"+REDDIT_SUBREDDIT

## MOVIEPY ###

MOVIEPY_VCODEC = "libx264"
MOVIEPY_QUALITY = "24"
MOVIEPY_COMPRESSION = "slow"
MOVIEPY_BACKGROUNDFILE = VIDEOS_FOLDER+"Background/"
MOVIEPY_OUTPUTFILE = VIDEOS_FOLDER+"Edited/edited-"
MOVIEPY_VIDEOCODEC = ".mp4"
MOVIEPY_WIDTH = 720
MOVIEPY_BORDERSIZE = 100
MOVIEPY_BORDERSIZEOUTER = 15
MOVIEPY_FONTSIZE = 75


### PEXELS ###


PEXELS_API_KEY = "563492ad6f91700001000001921ed6d820e944fd8281eb9dcfa09a57"
PEXELS_API_ENDPOINT = "https://api.pexels.com/videos/search"
PEXELS_API_ORIENTATION = 'portrait'
PEXELS_API_SIZE = "medium"
PEXELS_API_QUERY = "beer"
